--!strict
-- AUTO-GENERATED by tools/upload_email_avatars.py. Do not hand-edit.
-- Maps ScamCard ids to uploaded Roblox decal asset ids. Consumed by
-- ServerStorage.ScamCards at module load to populate sender.avatarImage.
--
-- Re-run the uploader after adding new avatars; this file is regenerated
-- from assets/email_avatars/upload_results.json.

local SenderArt = {}

-- card_id -> Roblox decal asset id (0 = not uploaded yet, fall back to color disc).
SenderArt.AssetIds = {
	["ai_hallucination_001"] = 117345981305056,
	["ai_hallucination_002"] = 132860955474605,
	["legit_bank_001"] = 71307768734105,
	["legit_github_001"] = 106374546599872,
	["legit_kindness_001"] = 126200671321170,
	["legit_newsletter_001"] = 104118739702423,
	["legit_recovery_001"] = 100022399094581,
	["legit_safety_report_001"] = 108380050709336,
	["legit_school_001"] = 75669684044237,
	["legit_shipping_001"] = 74375501978786,
	["mod_imposter_001"] = 97155104323912,
	["mod_imposter_002"] = 140005444261885,
	["phish_authority_001"] = 123497204724045,
	["phish_authority_002"] = 94683866232483,
	["phish_authority_003"] = 112251390359252,
	["phish_authority_004"] = 122765339922740,
	["phish_crypto_001"] = 131641763089978,
	["phish_curiosity_001"] = 116529994668565,
	["phish_curiosity_002"] = 100297446457233,
	["phish_familiarity_001"] = 94956415728037,
	["phish_familiarity_002"] = 81859345607247,
	["phish_fear_001"] = 113114385103935,
	["phish_fear_002"] = 136053993290681,
	["phish_payroll_001"] = 90050623557001,
	["phish_qr_001"] = 95255706028774,
	["phish_reward_001"] = 98725954456590,
	["phish_reward_002"] = 139001001297953,
	["phish_shared_doc_001"] = 114954893894383,
	["phish_spear_001"] = 83588614793034,
	["phish_urgency_001"] = 138254460801225,
	["phish_urgency_002"] = 108128936297124,
	["phish_urgency_003"] = 96995755203685,
	["rumor_health_001"] = 127857796034010,
	["rumor_school_001"] = 118133709568401,
} :: { [string]: number }

function SenderArt.Get(cardId: string): string?
	local id = SenderArt.AssetIds[cardId]
	if not id or id == 0 then
		return nil
	end
	return string.format("rbxassetid://%d", id)
end

function SenderArt.Has(cardId: string): boolean
	local id = SenderArt.AssetIds[cardId]
	return id ~= nil and id ~= 0
end

return SenderArt
