#!/usr/bin/env python3
"""Upload generated email avatar PNGs to Roblox via the Open Cloud Assets API,
cache the resulting asset ids, and regenerate SenderArt.lua.

Usage:
    # one-time: create an Open Cloud key with asset:read + asset:write at
    # https://create.roblox.com/dashboard/credentials and put it in .env:
    #   ROBLOX_API_KEY=...
    python3 tools/upload_email_avatars.py --user-id 1234567890
    # or for group-owned uploads:
    python3 tools/upload_email_avatars.py --group-id 9876543

Flags:
    --dry-run        list what would be uploaded, don't hit the API
    --regen-lua-only re-emit SenderArt.lua from cache without uploading
    --concurrency N  workers (default 4; Open Cloud allows ~60 RPM per key)
    --force          re-upload even if cache has a usable asset id
"""

from __future__ import annotations

import argparse
import concurrent.futures
import hashlib
import json
import os
import sys
import time
from pathlib import Path
from typing import Any

import requests


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
MANIFEST_PATH = ROOT / "assets" / "email_avatars" / "manifest.json"
RESULTS_PATH = ROOT / "assets" / "email_avatars" / "upload_results.json"
LUA_OUT_PATH = ROOT / "src" / "ReplicatedStorage" / "Modules" / "SenderArt.lua"

OPEN_CLOUD_BASE = "https://apis.roblox.com/assets/v1"
ASSET_ENDPOINT = f"{OPEN_CLOUD_BASE}/assets"
POLL_TIMEOUT_SECONDS = 300
POLL_INTERVAL_INITIAL = 1.0
POLL_INTERVAL_MAX = 15.0


def load_dotenv(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def load_manifest() -> list[dict[str, Any]]:
    if not MANIFEST_PATH.exists():
        sys.exit(f"manifest not found: {MANIFEST_PATH}")
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def load_results() -> dict[str, dict[str, Any]]:
    if not RESULTS_PATH.exists():
        return {}
    return json.loads(RESULTS_PATH.read_text(encoding="utf-8"))


def save_results(results: dict[str, dict[str, Any]]) -> None:
    RESULTS_PATH.write_text(
        json.dumps(results, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def upload_asset(
    *,
    api_key: str,
    creator: dict[str, str],
    card_id: str,
    png_path: Path,
) -> dict[str, Any]:
    request_body = {
        "assetType": "Decal",
        "displayName": f"PHISH email avatar - {card_id}",
        "description": f"Generated email avatar for ScamCard {card_id}",
        "creationContext": {"creator": creator},
    }
    files = {
        "request": (None, json.dumps(request_body), "application/json"),
        "fileContent": (png_path.name, png_path.read_bytes(), "image/png"),
    }
    headers = {"x-api-key": api_key}
    r = requests.post(ASSET_ENDPOINT, headers=headers, files=files, timeout=60)
    if r.status_code >= 400:
        raise RuntimeError(f"upload {card_id} failed [{r.status_code}]: {r.text}")
    payload = r.json()
    op_path = payload.get("path")
    if not op_path:
        raise RuntimeError(f"upload {card_id} missing operation path: {payload}")

    deadline = time.time() + POLL_TIMEOUT_SECONDS
    interval = POLL_INTERVAL_INITIAL
    while time.time() < deadline:
        time.sleep(interval)
        interval = min(interval * 1.6, POLL_INTERVAL_MAX)
        op = requests.get(f"{OPEN_CLOUD_BASE}/{op_path}", headers=headers, timeout=30)
        if op.status_code >= 400:
            raise RuntimeError(f"poll {card_id} failed [{op.status_code}]: {op.text}")
        op_payload = op.json()
        if not op_payload.get("done"):
            continue
        if "error" in op_payload:
            raise RuntimeError(f"asset {card_id} rejected: {op_payload['error']}")
        response = op_payload.get("response") or {}
        asset_id = response.get("assetId")
        if not asset_id:
            raise RuntimeError(f"asset {card_id} done but missing assetId: {op_payload}")
        return {"asset_id": str(asset_id), "operation_id": op_path, "raw": response}

    raise RuntimeError(f"asset {card_id} timed out after {POLL_TIMEOUT_SECONDS}s")


def lua_table(results: dict[str, dict[str, Any]]) -> str:
    lines: list[str] = [
        "--!strict",
        "-- AUTO-GENERATED by tools/upload_email_avatars.py. Do not hand-edit.",
        "-- Maps ScamCard ids to uploaded Roblox decal asset ids. Consumed by",
        "-- ServerStorage.ScamCards at module load to populate sender.avatarImage.",
        "--",
        "-- Re-run the uploader after adding new avatars; this file is regenerated",
        "-- from assets/email_avatars/upload_results.json.",
        "",
        "local SenderArt = {}",
        "",
        "-- card_id -> Roblox decal asset id (0 = not uploaded yet, fall back to color disc).",
        "SenderArt.AssetIds = {",
    ]
    for card_id in sorted(results.keys()):
        entry = results[card_id]
        asset_id = int(entry.get("asset_id") or 0)
        lines.append(f"\t[\"{card_id}\"] = {asset_id},")
    lines.extend(
        [
            "} :: { [string]: number }",
            "",
            "function SenderArt.Get(cardId: string): string?",
            "\tlocal id = SenderArt.AssetIds[cardId]",
            "\tif not id or id == 0 then",
            "\t\treturn nil",
            "\tend",
            "\treturn string.format(\"rbxassetid://%d\", id)",
            "end",
            "",
            "function SenderArt.Has(cardId: string): boolean",
            "\tlocal id = SenderArt.AssetIds[cardId]",
            "\treturn id ~= nil and id ~= 0",
            "end",
            "",
            "return SenderArt",
            "",
        ]
    )
    return "\n".join(lines)


def write_lua(results: dict[str, dict[str, Any]]) -> None:
    LUA_OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    LUA_OUT_PATH.write_text(lua_table(results), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    creator = p.add_mutually_exclusive_group()
    creator.add_argument("--user-id", help="Roblox user id (creator owner)")
    creator.add_argument("--group-id", help="Roblox group id (creator owner)")
    p.add_argument("--concurrency", type=int, default=4)
    p.add_argument("--force", action="store_true", help="re-upload even if cached")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--regen-lua-only", action="store_true",
                   help="rewrite SenderArt.lua from cache without uploading")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    load_dotenv(ENV_PATH)

    if args.regen_lua_only:
        results = load_results()
        write_lua(results)
        print(f"wrote {LUA_OUT_PATH.relative_to(ROOT)} from cache "
              f"({sum(1 for r in results.values() if r.get('asset_id'))}/{len(results)} populated)")
        return 0

    api_key = os.environ.get("ROBLOX_API_KEY")
    if not api_key and not args.dry_run:
        sys.exit("ROBLOX_API_KEY not set (put it in .env or export it)")

    if not args.dry_run:
        if args.user_id:
            creator = {"userId": str(args.user_id)}
        elif args.group_id:
            creator = {"groupId": str(args.group_id)}
        else:
            sys.exit("pass --user-id <id> or --group-id <id>")

    manifest = load_manifest()
    results = load_results()

    todo: list[dict[str, Any]] = []
    skipped = 0
    for entry in manifest:
        card_id = entry["card_id"]
        png_path = ROOT / entry["path"]
        if not png_path.exists():
            print(f"  skip {card_id}: missing {png_path}", file=sys.stderr)
            continue
        digest = sha256_of(png_path)
        cached = results.get(card_id)
        if (
            cached
            and cached.get("asset_id")
            and cached.get("sha256") == digest
            and not args.force
        ):
            skipped += 1
            continue
        todo.append({"card_id": card_id, "path": png_path, "sha256": digest})

    print(f"manifest={len(manifest)} todo={len(todo)} cached={skipped}")

    if args.dry_run:
        for item in todo:
            print(f"  would upload {item['card_id']:<35} <- {item['path'].name}")
        return 0

    if not todo:
        write_lua(results)
        print("nothing to upload; SenderArt.lua refreshed from cache.")
        return 0

    failures: list[tuple[str, str]] = []
    completed = 0

    def worker(item: dict[str, Any]) -> tuple[str, dict[str, Any] | None, str | None]:
        try:
            res = upload_asset(
                api_key=api_key,
                creator=creator,
                card_id=item["card_id"],
                png_path=item["path"],
            )
            res["sha256"] = item["sha256"]
            res["source_path"] = str(item["path"].relative_to(ROOT))
            res["uploaded_at"] = int(time.time())
            res["status"] = "uploaded"
            return item["card_id"], res, None
        except Exception as exc:  # noqa: BLE001
            return item["card_id"], None, str(exc)

    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, args.concurrency)) as pool:
        futures = [pool.submit(worker, item) for item in todo]
        for fut in concurrent.futures.as_completed(futures):
            card_id, res, err = fut.result()
            if err or not res:
                failures.append((card_id, err or "unknown"))
                print(f"  FAIL {card_id}: {err}")
            else:
                results[card_id] = res
                save_results(results)
                completed += 1
                print(f"  ok   {card_id} -> {res['asset_id']}  ({completed}/{len(todo)})")

    write_lua(results)

    print(f"done: uploaded={completed} failed={len(failures)} cache_total="
          f"{sum(1 for r in results.values() if r.get('asset_id'))}")
    if failures:
        print("failures:", file=sys.stderr)
        for card_id, err in failures:
            print(f"  {card_id}: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
